### ISSUE TITLE
Issue #1: Speech to text title 

### ISSUE THREAD

**Issue by Dantusaikamal** [mg143pavankumar/Speech-To-Text#1]
_**Speech to text in the first line is not showing properly**_

**Comment by Dantusaikamal** [comment]
![Screenshot_2020-07-15-11-42-43-246_com android chrome](https://user-images.githubusercontent.com/65682028/87511636-3af75000-c693-11ea-9e3a-1fe072750b75.jpg)

**Comment by mistrypavankumar** [comment]
![title](https://user-images.githubusercontent.com/68140538/87513418-59127f80-c696-11ea-9f4b-7566a93537f5.PNG)

**Comment by mistrypavankumar** [comment]
This issue is fixed
